-- Dropping a database stuck in recovery
-- MAKE SURE YOU ARE ON THE CORRECT NODE!!!
SELECT @@ServerName AS SERVERNAME

-- https://www.brentozar.com/archive/2016/06/availability-group-direct-seeding-fix-database-wont-sync/
--ALTER DATABASE [HSP] SET HADR RESUME;  -- THIS WONT WORK

ALTER AVAILABILITY GROUP [PVHAGHSP] REMOVE DATABASE [HSP]
GO

ALTER AVAILABILITY GROUP [PVHAGHSP] ADD DATABASE [HSP]
GO

ALTER DATABASE HSP SET EMERGENCY
go
DBCC CHECKDB (N'HSP', REPAIR_ALLOW_DATA_LOSS) WITH ALL_ERRORMSGS, NO_INFOMSGS;
GO

RESTORE DATABASE [HSP] WITH RECOVERY
GO

USE [master]
GO

DROP AVAILABILITY GROUP [PVHAGHSP01];
GO


ALTER DATABASE [HSP] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DROP DATABASE [HSP]
GO

-- IF NONE OF THE ABOVE WORKS GO TO OS AND FROM ADMIN CMD PROMPT KILL SQLSERVER SERVICE
-- C:\>tasklist | more
-- C:\>taskkill /F /PID 2208
-- DELETE THE MDF,NDF, LDF
-- START SQL 
