--
-- https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-read-only-routing-for-an-availability-group-sql-server
--SECONDARY ROLE
ALTER AVAILABILITY GROUP [QVHAGHSP01]  
 MODIFY REPLICA ON N'QVSQLHSP01' WITH   
	(SECONDARY_ROLE (ALLOW_CONNECTIONS = READ_ONLY));  
ALTER AVAILABILITY GROUP [QVHAGHSP01]  
 MODIFY REPLICA ON  N'QVSQLHSP01' WITH   
	(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://QVSQLHSP01.iehp.local:1433'));  

ALTER AVAILABILITY GROUP [QVHAGHSP01]  
 MODIFY REPLICA ON  N'QVSQLHSP02' WITH   
	(SECONDARY_ROLE (ALLOW_CONNECTIONS = READ_ONLY));  
ALTER AVAILABILITY GROUP [QVHAGHSP01]  
 MODIFY REPLICA ON  N'QVSQLHSP02' WITH   
	(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://QVSQLHSP02.iehp.local:1433'));

--PRIMARY ROLE
ALTER AVAILABILITY GROUP [QVHAGHSP01]   
MODIFY REPLICA ON  N'QVSQLHSP01' WITH   
	(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('QVSQLHSP02')));  

ALTER AVAILABILITY GROUP [QVHAGHSP01]   
MODIFY REPLICA ON  N'QVSQLHSP02' WITH   
	(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('QVSQLHSP02')));  
GO  
