USE HSP
go
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
SET STATISTICS IO, TIME ON

ALTER INDEX ALL ON [HSP].[dbo].[ClaimDetails] REBUILD WITH (SORT_IN_TEMPDB = OFF, ONLINE = ON)
GO
PRINT '***REBUILD COMPLETE***'
UPDATE STATISTICS [HSP].[dbo].[ClaimDetails] WITH FULLSCAN
GO
PRINT '***STATS COMPLETE***'
go
SET STATISTICS IO, TIME OFF
go
