USE HSP_RPT;
GO
SELECT T.TABLE_CATALOG DATABASE_NAME,
       T.TABLE_SCHEMA AS SCHEMA_NAME,
       T.TABLE_NAME,
       C.COLUMN_NAME,
       C.DATA_TYPE DATA_TYPE,
       C.CHARACTER_MAXIMUM_LENGTH MAXIMUM_LENGTH,
       C.COLLATION_NAME
FROM INFORMATION_SCHEMA.COLUMNS C
    INNER JOIN INFORMATION_SCHEMA.TABLES T
        ON C.TABLE_SCHEMA = T.TABLE_SCHEMA
           AND C.TABLE_NAME = T.TABLE_NAME
WHERE T.TABLE_TYPE = 'BASE TABLE'
      AND
      (
          (
              C.DATA_TYPE IN ( 'VARCHAR', 'NVARCHAR' )
              AND C.CHARACTER_MAXIMUM_LENGTH = -1
          )
          OR DATA_TYPE IN ( 'TEXT', 'NTEXT', 'IMAGE', 'VARBINARY', 'XML', 'FILESTREAM' )
      )
      AND T.TABLE_SCHEMA NOT IN ( 'CDC' ) -- EXCEPTION LIST
ORDER BY T.TABLE_SCHEMA,
         T.TABLE_NAME;
GO
