ALTER AVAILABILITY GROUP [PVHAGHSP01]
MODIFY REPLICA ON
N'HSP1S1A' WITH
(SECONDARY_ROLE (ALLOW_CONNECTIONS = READ_ONLY));

ALTER AVAILABILITY GROUP [PVHAGHSP01]
MODIFY REPLICA ON
N'HSP1S1A' WITH
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://HSP1S1A.iehp.local:1433'));

ALTER AVAILABILITY GROUP [PVHAGHSP01]
MODIFY REPLICA ON
N'HSP1S1B' WITH
(SECONDARY_ROLE (ALLOW_CONNECTIONS = READ_ONLY));

ALTER AVAILABILITY GROUP [PVHAGHSP01]
MODIFY REPLICA ON
N'HSP1S1B' WITH
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://HSP1S1B.iehp.local:1433'));

ALTER AVAILABILITY GROUP [PVHAGHSP01]
MODIFY REPLICA ON
N'HSP1S1A' WITH
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('SQLNODE03','HSP1S1B')));

ALTER AVAILABILITY GROUP [PVHAGHSP01]
MODIFY REPLICA ON
N'HSP1S1B' WITH
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('SQLNODE03','HSP1S1A')));


ALTER AVAILABILITY GROUP [PVHAGHSP01]
MODIFY REPLICA ON
N'HSP1S1A' WITH
(PRIMARY_ROLE
(READ_ONLY_ROUTING_LIST=(('HSP1S1B','SQLNODE03'),('SQLNODE04','SQLNODE05','SQLNODE06'),'SQLNODE07')));

