-- 1 RESTORE WILL FAIL IF THERE IS NO MASTER KEY AND RESTORED CERTIFICATES FROM PRIMARY
USE [master]
RESTORE DATABASE [HSP] FROM  DISK = N'E:\MSSQL\Backup\HSP_TDE_full.bak' 
WITH  
	FILE = 1,  
	NOUNLOAD,  
	REPLACE,  
	STATS = 5

GO
-- 2 CHECK FOR THE EXISTENCE OF A DMK
USE master; 
GO
SELECT  *
FROM    sys.symmetric_keys
WHERE   name = '##MS_DatabaseMasterKey##';
GO

-- 3 IF NO DMK EXISTSY CREATE ONE EACH NODE 
CREATE MASTER KEY ENCRYPTION BY PASSWORD =
    '4EAC97F9-6C85-4204-83B6-5757D325A557';
GO

-- 4 ON EACH SECONDARY REPLICA INSTANCE, CREATE THE TDE CERTIFICATE FROM THE CERTIFICATE BACKED UP ON THE PRIMARY
--   COPY FILES TO EACH SERVER AND REMEMBER TO SAVE THEM ONLY ON APPROVED DRIVES AND UNC's
GO
USE master
GO
CREATE CERTIFICATE QVSQLHSP_MasterCert 
	FROM FILE = 'E:\MSSQL\Backup\QVSQLHSP_MasterCert.bak' 
	WITH PRIVATE KEY ( 
		FILE = 'E:\MSSQL\Backup\QVSQLHSP_MasterCert.pvk', 
		DECRYPTION BY PASSWORD = '4EAC97F9-6C85-4204-83B6-5757D325A557');
GO

-- 5 NOW YOU CAN RESTORE
USE [master]
RESTORE DATABASE [HSP] FROM  DISK = N'E:\MSSQL\Backup\HSP_TDE_full.bak' 
WITH  
	FILE = 1,  
	NOUNLOAD,  
	REPLACE,  
	STATS = 5

GO
-- RESTORE 4.13 GB TDE BAK DURATION: 00:02:59
