USE dbatools
go
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
SET STATISTICS IO, TIME ON
GO
ALTER INDEX [PK_SqlServerVersions] ON [dbo].[SqlServerVersions] REORGANIZE  WITH ( LOB_COMPACTION = ON )
GO
PRINT '***REORGANIZE COMPLETE***'
ALTER INDEX ALL ON [dbatools].[dbo].[SqlServerVersions] REBUILD WITH (SORT_IN_TEMPDB = OFF, ONLINE = ON)
--ALTER INDEX [PK_SqlServerVersions] ON [dbo].[SqlServerVersions] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
PRINT '***REBUILD COMPLETE***'
UPDATE STATISTICS [dbatools].[dbo].[SqlServerVersions] WITH FULLSCAN
GO
PRINT '***STATS COMPLETE***'
go
SET STATISTICS IO, TIME OFF
go
