SELECT * FROM sys.dm_os_sys_info
SELECT * FROM sys.dm_os_sys_memory
SELECT * FROM sys.dm_os_process_memory
SELECT * FROM sys.dm_os_memory_clerks
SELECT * FROM sys.dm_os_memory_nodes
SELECT * FROM sys.dm_os_memory_pools
SELECT * FROM sys.dm_os_memory_brokers
SELECT * FROM sys.dm_os_memory_cache_clock_hands
SELECT * FROM sys.dm_exec_query_memory_grants
