
EXEC sp_resetstatus CHANGEGEAR;
ALTER DATABASE CHANGEGEAR SET EMERGENCY
DBCC checkdb(CHANGEGEAR)
ALTER DATABASE CHANGEGEAR SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DBCC CheckDB (CHANGEGEAR, REPAIR_ALLOW_DATA_LOSS)
ALTER DATABASE CHANGEGEAR SET MULTI_USER

--SET BACK
ALTER DATABASE CHANGEGEAR SET SINGLE_USER;
GO
DBCC CHECKDB (CHANGEGEAR, REPAIR_ALLOW_DATA_LOSS) WITH NO_INFOMSGS; 
Go
Alter DATABASE CHANGEGEAR set MULTI_USER