SELECT GETDATE(), @@SERVERNAME

SET STATISTICS TIME ON
SET STATISTICS IO ON

BACKUP DATABASE [HSP]
TO  DISK = N'\\dtsqlbkups\qvsqllit01backups\Production\HSP1S1B\HSP_MonthEnd.me' --WE PURPOSELY DID NOT ADD EXTENSION .BAK SO IT DOES NOT GET DELETED WITH CLEANUP JOB
WITH NOFORMAT
   , COPY_ONLY --COPY_ONLY!! -- **** MUST BE COPY_ONLY TO NOT BREAK THE CHAIN ****
   , NOINIT
   , NAME = N'HSP MONTH END -COPY-ONLY Database Backup'
   , SKIP
   , NOREWIND
   , NOUNLOAD
   , COMPRESSION
   , MAXTRANSFERSIZE = 4194304
   , BUFFERCOUNT = 2048
   , STATS = 1;
GO

SELECT GETDATE(), @@SERVERNAME

SET STATISTICS TIME OFF
SET STATISTICS IO OFF

