SET STATISTICS TIME, IO ON;
GO
DBCC TRACEON(3004, 3051, 3212, 3014, 3605, 1816, -1); --TO BE USED ONLY FOR DEBUGGING
GO
PRINT 'START DT: ' + (CONVERT(VARCHAR(24), GETDATE(), 121));
GO
DECLARE @exitcode int
DECLARE @sqlerrorcode int
EXECUTE master..sqlbackup '-SQL "BACKUP DATABASES [Member] TO DISK = ''\\DTSQLBKUPS\EntDataSystems\Non-Production\BAK\QVSQLEDI01\<AUTO>.sqb'' 
WITH 
INIT
, ERASEFILES_PRIMARY = 6
, PASSWORD = ''<OBFUSCATEDPASSWORD>yuS0TJ5HNVGezIxzc4W4TOQDTWQ=</OBFUSCATEDPASSWORD>''
, MAXTRANSFERSIZE = 1048576
, BUFFERCOUNT = 1024
, DISKRETRYINTERVAL = 30
, DISKRETRYCOUNT = 0
, COMPRESSION = 3
, FILECOUNT = 10
, KEYSIZE = 256"', @exitcode OUT, @sqlerrorcode OUT
IF (@exitcode >= 500) OR (@sqlerrorcode <> 0)
BEGIN
RAISERROR ('SQL Backup failed with exit code: %d  SQL error code: %d', 16, 1, @exitcode, @sqlerrorcode)
END
GO
PRINT 'END DT: ' + (CONVERT(VARCHAR(24), GETDATE(), 121));
GO
DBCC TRACEOFF(3004, 3051, 3212, 3014, 3605, 1816, -1);
GO
SET STATISTICS TIME, IO OFF;
GO