
--SELECT COUNT(*) FROM  [CQ].[FilesTransactions]
USE [ACH_Claims]
GO
EXECUTE AS USER = 'iehp\i4666'
SELECT SUSER_NAME(), USER_NAME()

SELECT *  FROM [dbo].[tblACH]
GO

REVERT;
SELECT SUSER_NAME(), USER_NAME()
REVERT;
GO
SELECT SUSER_NAME(), USER_NAME()
GO
REVERT;
GO
SELECT SUSER_NAME(), USER_NAME()
USE [ACH_Claims]
GO
SELECT *  FROM [dbo].[tblACH]
GO

