--2012 +
USE [master]
GO
CREATE LOGIN [QSQLLITESPEED] WITH PASSWORD=N'leIlq0a4eOtfw0ybHz3C' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [QSQLLITESPEED]
GO

--2008 R2
USE [master]
GO
CREATE LOGIN [QSQLLITESPEED] WITH PASSWORD=N'leIlq0a4eOtfw0ybHz3C', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO
EXEC master..sp_addsrvrolemember @loginame = N'QSQLLITESPEED', @rolename = N'sysadmin'
GO
