SET NOCOUNT ON;
SELECT is_broker_enabled
FROM sys.databases
WHERE name = 'HSP_QA2';
PRINT 'is_broker_enabled #1 COMPLETED';
GO
ALTER DATABASE HSP_QA2 SET DISABLE_BROKER;
PRINT 'disable_broker COMPLETED';
GO
ALTER DATABASE HSP_QA2 SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE;
PRINT 'ENABLE_BROKER COMPLETED';
GO
ALTER DATABASE HSP_QA2 SET NEW_BROKER;
PRINT 'NEW_BROKER COMPLETED';
GO
SELECT is_broker_enabled
FROM sys.databases
WHERE name = 'HSP_QA2';
PRINT 'is_broker_enabled #2 COMPLETED';
GO
sp_changedbowner HSP_dbo;
PRINT 'sp_changedbowner COMPLETED';
GO
