Exec xp_logininfo 'IEHP\HSP3DataReader', 'members'
Exec xp_logininfo 'IEHP\HSP3Admins', 'members'

SETUSER 'IEHP\HSP3DataReader'
GO
USE HSP_IT_SB
GO
SETUSER
GO

EXECUTE AS LOGIN = 'IEHP\HSP3DataReader';
GO
USE HSP_IT_SB
GO
REVERT
GO

SELECT * from sys.login_token

SELECT * FROM sys.user_token

DECLARE @varbinaryField varbinary(max);
SET @varbinaryField = 0x010500000000000515000000A36F8A42E3060D580A79F072A7690000;

SELECT CONVERT(varchar(max),@varbinaryField,2), @varbinaryField

-- https://technet.microsoft.com/en-us/library/ms191153.aspx#Manual
--setspn -A MSSQLSvc/myhost.redmond.microsoft.com:1433 accountname  

SELECT net_transport, auth_scheme   
FROM sys.dm_exec_connections   
WHERE session_id = @@SPID;  


-- https://technet.microsoft.com/en-us/library/ms191153.aspx#Manual
--PERMISSIONS
--WHEN THE DATABASE ENGINE SERVICE STARTS, IT ATTEMPTS TO REGISTER THE SERVICE PRINCIPAL NAME (SPN). 
--IF THE ACCOUNT STARTING SQL SERVER DOESN’T HAVE PERMISSION TO REGISTER A SPN IN ACTIVE DIRECTORY DOMAIN 
--SERVICES, THIS CALL WILL FAIL AND A WARNING MESSAGE WILL BE LOGGED IN THE APPLICATION EVENT LOG AS WELL 
--AS THE SQL SERVER ERROR LOG. TO REGISTER THE SPN, THE DATABASE ENGINE MUST BE RUNNING UNDER A BUILT-IN 
--ACCOUNT, SUCH AS LOCAL SYSTEM (NOT RECOMMENDED), OR NETWORK SERVICE, OR AN ACCOUNT THAT HAS PERMISSION 
--TO REGISTER AN SPN, SUCH AS A DOMAIN ADMINISTRATOR ACCOUNT. WHEN SQL SERVER IS RUNNING ON THE WINDOWS 7 
--OR WINDOWS SERVER 2008 R2 OPERATING SYSTEM, YOU CAN RUN SQL SERVER USING A VIRTUAL ACCOUNT OR A MANAGED 
--SERVICE ACCOUNT (MSA). BOTH VIRTUAL ACCOUNTS AND MSA’S CAN REGISTER AN SPN. IF SQL SERVER IS NOT RUNNING 
--UNDER ONE OF THESE ACCOUNTS, THE SPN IS NOT REGISTERED AT STARTUP AND THE DOMAIN ADMINISTRATOR MUST 
--REGISTER THE SPN MANUALLY.
