USE [Master]
GO

CREATE LOGIN [MYDOMAIN\APPLICATION SUPPORT] FROM WINDOWS
GO

USE [Accounting]
GO

CREATE USER [MYDOMAIN\APPLICATION SUPPORT] FROM LOGIN [MYDOMAIN\APPLICATION SUPPORT]
GO

CREATE ROLE [SQLUser]
GO

EXEC sp_addrolemember 'SQLUser', 'A91\SQLUserGroup'
GO

GRANT SELECT ON [Objects in IGT DB] TO [SQLUser]
GO


