-- List Parent Table

DECLARE @mytable VARCHAR(30)

SET @mytable = 'Account'

SELECT t2.TABLE_NAME AS PointTo
	, t1.TABLE_NAME AS PointsFrom
	, t1.CONSTRAINT_NAME AS ConstraintName
	, t1.CONSTRAINT_TYPE AS ConstraintType
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS r
INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS t1
	ON t1.CONSTRAINT_NAME = r.CONSTRAINT_NAME
INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS t2
	ON t2.CONSTRAINT_NAME = r.UNIQUE_CONSTRAINT_NAME
WHERE t2.table_name = @mytable
