-- List PK & FK in Database

SELECT CONVERT(SYSNAME, DB_NAME()) AS 'PK Table Qualifier'
	, CONVERT(SYSNAME, SCHEMA_NAME(O1.SCHEMA_ID)) AS 'PK Table Owner'
	, CONVERT(SYSNAME, O1.NAME) AS 'PK Table Name'
	, CONVERT(SYSNAME, C1.NAME) AS 'PK Column Name'
	, CONVERT(SYSNAME, DB_NAME()) AS 'FK Table Qualifier'
	, CONVERT(SYSNAME, SCHEMA_NAME(O2.SCHEMA_ID)) AS 'FK Table Owner'
	, CONVERT(SYSNAME, O2.NAME) AS 'FK Table Name'
	, CONVERT(SYSNAME, C2.NAME) AS 'FK Column Name'
	, CONVERT(SMALLINT, CASE OBJECTPROPERTY(F.OBJECT_ID, 'CnstIsUpdateCascade')
			WHEN 1
				THEN 0
			ELSE 1
			END) AS 'Update Rule'
	, CONVERT(SMALLINT, CASE OBJECTPROPERTY(F.OBJECT_ID, 'CnstIsDeleteCascade')
			WHEN 1
				THEN 0
			ELSE 1
			END) AS 'Delete Rule'
	, CONVERT(SYSNAME, OBJECT_NAME(F.OBJECT_ID)) AS 'FK Name'
	, CONVERT(SYSNAME, I.NAME) AS 'PK Name'
	, CONVERT(SMALLINT, 7) AS 'Deferrability'
FROM SYS.ALL_OBJECTS O1
	, SYS.ALL_OBJECTS O2
	, SYS.ALL_COLUMNS C1
	, SYS.ALL_COLUMNS C2
	, SYS.FOREIGN_KEYS F
INNER JOIN SYS.FOREIGN_KEY_COLUMNS K
	ON (K.CONSTRAINT_OBJECT_ID = F.OBJECT_ID)
INNER JOIN SYS.INDEXES I
	ON (
			F.REFERENCED_OBJECT_ID = I.OBJECT_ID
			AND F.KEY_INDEX_ID = I.INDEX_ID
			)
WHERE O1.OBJECT_ID = F.REFERENCED_OBJECT_ID
	AND O2.OBJECT_ID = F.PARENT_OBJECT_ID
	AND C1.OBJECT_ID = F.REFERENCED_OBJECT_ID
	AND C2.OBJECT_ID = F.PARENT_OBJECT_ID
	AND C1.COLUMN_ID = K.REFERENCED_COLUMN_ID
	AND C2.COLUMN_ID = K.PARENT_COLUMN_ID
