-- List all Tables in Database

DECLARE @DBName varchar(30)

SET @DBName = 'EX'

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
	AND TABLE_CATALOG = @DBName
ORDER BY TABLE_NAME	
