-- List Constrain Name by Table

SELECT TBL.TABLE_SCHEMA AS Constrained_TABLE_SCHEMA
	, TBL.TABLE_NAME AS Constrained_TABLE_NAME
	, FK.CONSTRAINT_NAME
	, FK.UNIQUE_CONSTRAINT_SCHEMA
	, FK.UNIQUE_CONSTRAINT_NAME
	, RefKey.TABLE_SCHEMA AS Referenced_TABLE_SCHEMA
	, RefKey.TABLE_NAME AS Referenced_TABLE_NAME
	, FK.MATCH_OPTION
	, FK.UPDATE_RULE
	, FK.DELETE_RULE
	, LEFT(FKC.FKColumnList, LEN(FKC.FKColumnList) - 1) AS Foreign_Key_Column_List
	, LEFT(UQC.UQColumnList, LEN(UQC.UQColumnList) - 1) AS Referenced_Key_Column_List
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TBL
INNER JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS FK
	ON FK.CONSTRAINT_CATALOG = TBL.CONSTRAINT_CATALOG
		AND FK.CONSTRAINT_SCHEMA = TBL.CONSTRAINT_SCHEMA
		AND FK.CONSTRAINT_NAME = TBL.CONSTRAINT_NAME
INNER JOIN INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE AS RefKey
	ON RefKey.CONSTRAINT_CATALOG = FK.UNIQUE_CONSTRAINT_CATALOG
		AND RefKey.CONSTRAINT_SCHEMA = FK.UNIQUE_CONSTRAINT_SCHEMA
		AND RefKey.CONSTRAINT_NAME = FK.UNIQUE_CONSTRAINT_NAME
CROSS APPLY (
	SELECT '[' + FKColumns.COLUMN_NAME + '],'
	FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE FKColumns
	WHERE FKColumns.CONSTRAINT_CATALOG = FK.CONSTRAINT_CATALOG
		AND FKColumns.CONSTRAINT_SCHEMA = FK.CONSTRAINT_SCHEMA
		AND FKColumns.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
	ORDER BY FKColumns.ORDINAL_POSITION
	FOR XML PATH('')
	) FKC(FKColumnList)
CROSS APPLY (
	SELECT '[' + UQColumns.COLUMN_NAME + '],'
	FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE UQColumns
	WHERE UQColumns.CONSTRAINT_CATALOG = FK.UNIQUE_CONSTRAINT_CATALOG
		AND UQColumns.CONSTRAINT_SCHEMA = FK.UNIQUE_CONSTRAINT_SCHEMA
		AND UQColumns.CONSTRAINT_NAME = FK.UNIQUE_CONSTRAINT_NAME
	ORDER BY UQColumns.ORDINAL_POSITION
	FOR XML PATH('')
	) UQC(UQColumnList)
	ORDER BY Constrained_TABLE_NAME
