-- List Index Name and Columns Names

SELECT TABLENAME AS 'Table Name'
	, INDEXNAME AS 'Index Name'
	, INDEX_ID AS 'Index ID'
	, [1] AS 'Col1'
	, [2] AS 'Col2'
	, [3] AS 'Col3'
	, [4] AS 'Col4'
	, [5] AS 'Col5'
	, [6] AS 'Col6'
	, [7] AS 'Col7'
	, [8] AS 'Col8'
FROM (
	SELECT A.NAME AS TABLENAME
		, A.OBJECT_ID
		, B.NAME AS INDEXNAME
		, B.INDEX_ID
		, D.NAME AS COLUMNNAME
		, C.KEY_ORDINAL
	FROM SYS.OBJECTS A
	INNER JOIN SYS.INDEXES B
		ON A.OBJECT_ID = B.OBJECT_ID
	INNER JOIN SYS.INDEX_COLUMNS C
		ON B.OBJECT_ID = C.OBJECT_ID
			AND B.INDEX_ID = C.INDEX_ID
	INNER JOIN SYS.COLUMNS D
		ON C.OBJECT_ID = D.OBJECT_ID
			AND C.COLUMN_ID = D.COLUMN_ID
	WHERE A.TYPE <> 'S'
	) P
PIVOT(MIN(COLUMNNAME) FOR KEY_ORDINAL IN ([1], [2], [3], [4], [5], [6], [7], [8])) AS PVT
WHERE EXISTS (
		SELECT OBJECT_ID
			, INDEX_ID
		FROM SYS.DM_DB_INDEX_USAGE_STATS B
		WHERE DATABASE_ID = DB_ID(DB_NAME())
			AND PVT.OBJECT_ID = B.OBJECT_ID
			AND PVT.INDEX_ID = B.INDEX_ID
		)
ORDER BY TABLENAME
	, INDEXNAME;