--SYSTEM TEAM BACKUPS
USE [master]
GO
CREATE LOGIN [IEHP\svcExBackups] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [IEHP\svcExBackups]
GO

----SOLARWINDS ACCOUNT
--USE [master]
--GO
--CREATE LOGIN [IEHP\solaradmin] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
--GO
--ALTER SERVER ROLE [sysadmin] ADD MEMBER [IEHP\solaradmin]
--GO

