USE [master]
GO

/****** Object:  Database [DBAKit]    Script Date: 3/25/2021 1:55:06 PM ******/
CREATE DATABASE [DBAKit]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBAKit', FILENAME = N'E:\DATA\DBAKit.mdf' , SIZE = 524288KB , MAXSIZE = 5242880KB , FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'DBAKit_log', FILENAME = N'L:\Log\DBAKit_log.ldf' , SIZE = 524288KB , MAXSIZE = 3145728KB , FILEGROWTH = 524288KB )
GO

ALTER DATABASE [DBAKit] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBAKit].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBAKit] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBAKit] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBAKit] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBAKit] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBAKit] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBAKit] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBAKit] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBAKit] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBAKit] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBAKit] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBAKit] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBAKit] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBAKit] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBAKit] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBAKit] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DBAKit] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBAKit] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBAKit] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBAKit] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBAKit] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBAKit] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBAKit] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBAKit] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBAKit] SET  MULTI_USER 
GO

ALTER DATABASE [DBAKit] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBAKit] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBAKit] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBAKit] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBAKit] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBAKit] SET QUERY_STORE = OFF
GO

USE [DBAKit]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [DBAKit] SET  READ_WRITE 
GO


